# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H-sBjqZn14L-UjfdqzPLZS4_s2L6U7Hk
"""

n=int(input())
num=n
count=0
while True:
    a=num//10
    b=num%10
    c=(a+b)%10
    d=(b*10)+c
    count=count+1
    if d==n:
        break
print(count)