# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H-sBjqZn14L-UjfdqzPLZS4_s2L6U7Hk
"""

H,M=map(int,input().split())
0<=H<=23
0<=M<=59

if M<45:
    if H==0:
        H=23
        M+=60
    else:
        H-=1
        M+=60

print(H,M-45)