# -*- coding: utf-8 -*-
"""avg.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14xeOanXycWExA5R4FcULghzeOkdj1nNw
"""

# 평균은 되겠지
n = int(input())

for _ in range(n) :
    nums = list(map(int, input().split()))
    avg = sum(nums[1:])/nums[0]
    cnt = 0
    for score in nums[1:] :
        if score > avg :
            cnt += 1 
    rate = (cnt/nums[0]) *100
    # print(f'{rate:.3f}%')
    # print(round(rate, 3))