# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NVgReQkcKWk9cMSrUmhZLjAkb80DmfwC
"""

aint = int(input(""))
(0<= aint <= 99)
num = aint
count = 0
while True :
    a = num&10 + num//10
    num = (a&10 + a//10)&10 + (a&10 + a//10)//10
    count += 1
    if num == aint or a == aint :
        print(count)
        break

