# -*- coding: utf-8 -*-
"""상수.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14xeOanXycWExA5R4FcULghzeOkdj1nNw
"""

#상수
a = int(input())
b = int(input())

a1 = []
b1 = []
a = str(a)
b = str(b)
for i in a :
    a1.append(i)
for i in b :
    b1.append(i)

a_copy = a1.copy()
b_copy = b1.copy()

a_copy[0] = a1[2]
a_copy[2] = a1[0]
b_copy[0] = b1[2]
b_copy[2] = b1[0]

a2 = a_copy[0] + a_copy[1] + a_copy[2]
b2 = b_copy[0] + b_copy[1] + b_copy[2]
a2 = int(a2)
b2 = int(b2)

if a2 > b2 :
    print(a2)
else :
    print(b2)