# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10GHWaw681WTvS0MSaGQd93YMST-viltk
"""

# boj 4344


C = int(input())                                # 5

for i in range(C) :                             # 5번 반복
    scores = list(map(int, input().split()))    # 5 50 50 70 80 100
    avg = sum(scores[1:]) / scores[0]           # (50 + 50 + 70 + 80 + 100) / 5 = 70

    cnt = 0
    for j in scores[1:] :                       # 50, 50, 70, 80, 100에 대해 반복
        if j > avg :                            # 50 > 70이면
            cnt += 1
    result = cnt / scores[0] * 100
    print("%.3f" % result + "%")

