# -*- coding: utf-8 -*-
"""Boj1152

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YFzw46Y7lhu93jm4JTtcEzwVUel78nzm

### Boj 1152
"""

a = list(map(str,input().split()))

b = 0

for i in a:

    b += 1

print(b)