# -*- coding: utf-8 -*-
"""Boj15596

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YFzw46Y7lhu93jm4JTtcEzwVUel78nzm

### Boj 15596
"""

def solve(a):

    b = list()

    for i in a :

        b.append(i)

    return sum(b)