# -*- coding: utf-8 -*-
"""Boj2577

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YFzw46Y7lhu93jm4JTtcEzwVUel78nzm

### Boj 2577
"""

a = int(input())

b = int(input())

c = int(input())

 

total = a * b * c

 

s = list(str(total))

for i in range(10) :

    print(s.count(str(i)))